const lessonTitle = "长河落日扁";

const lessonData = [
    // ===== 第1段 =====
    ["王维", "wáng wéi", "Wang Wei", "Wang Wei"],
    ["《", "", "", ""],
    ["使至塞上", "shǐ zhì sài shàng", "On a Mission to the Frontier", "Dalam Perjalanan ke Sempadan"],
    ["》", "", "", ""],
    ["中", "zhōng", "in", "dalam"],
    ["有", "yǒu", "there are", "terdapat"],
    ["两句", "liǎng jù", "two lines", "dua ayat"],
    ["流传千古", "liú chuán qiān gǔ", "immortal", "terkenal selama-lamanya"],
    ["的", "de", "", ""],
    ["诗句", "shī jù", "verses", "rangkap puisi"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["大漠孤烟直", "dà mò gū yān zhí", "Lonely smoke rises straight in the vast desert", "Asap sunyi naik lurus di padang pasir"],
    ["，", "", "", ""],
    ["长河落日圆", "cháng hé luò rì yuán", "The setting sun is round over the long river", "Matahari terbenam bulat di atas sungai panjang"],
    ["。”", "", "", ""],
    ["诗中", "shī zhōng", "In the poem", "Dalam puisi itu"],
    ["运用了", "yùn yòng le", "used", "menggunakan"],
    ["精炼的", "jīng liàn de", "refined", "yang ringkas"],
    ["笔墨", "bǐ mò", "brushwork", "penulisan"],
    ["，", "", "", ""],
    ["勾画出", "gōu huà chū", "delineate", "melukiskan"],
    ["大漠", "dà mò", "desert", "padang pasir"],
    ["奇特壮观", "qí tè zhuàng guān", "unique and magnificent", "aneh dan megah"],
    ["的", "de", "", ""],
    ["景色", "jǐng sè", "scenery", "pemandangan"],
    ["。", "", "", ""],
    ["圆圆的", "yuán yuán de", "Round", "Bulat"],
    ["落日", "luò rì", "setting sun", "matahari terbenam"],
    ["，", "", "", ""],
    ["在", "zài", "on", "di"],
    ["大漠的", "dà mò de", "desert's", "padang pasir punya"],
    ["长河之上", "cháng hé zhī shàng", "long river", "sungai panjang"],
    ["，", "", "", ""],
    ["显得", "xiǎn de", "appears", "kelihatan"],
    ["格外醒目", "gé wài xǐng mù", "particularly striking", "sangat menarik"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "But", "Tetapi"],
    ["，", "", "", ""],
    ["你可曾想到", "nǐ kě céng xiǎng dào", "have you ever thought", "pernahkah awak terfikir"],
    ["，", "", "", ""],
    ["在", "zài", "in", "pada"],
    ["某种", "mǒu zhǒng", "certain", "tertentu"],
    ["特定的", "tè dìng de", "specific", "khas"],
    ["环境下", "huán jìng xià", "environment", "persekitaran"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["红彤彤的", "hóng tōng tōng de", "red", "merah"],
    ["落日", "luò rì", "setting sun", "matahari terbenam"],
    ["，", "", "", ""],
    ["并不一定", "bìng bù yī dìng", "not necessarily", "tidak semestinya"],
    ["是", "shì", "is", "ialah"],
    ["圆的", "yuán de", "round", "bulat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["其实", "qí shí", "In fact", "Sebenarnya"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["在", "zài", "at", "di"],
    ["海边", "hǎi biān", "seaside", "tepi laut"],
    ["、", "", "", ""],
    ["沙漠中", "shā mò zhōng", "desert", "padang pasir"],
    ["或", "huò", "or", "atau"],
    ["平原上", "píng yuán shàng", "plain", "dataran"],
    ["，", "", "", ""],
    ["在", "zài", "at", "pada"],
    ["日出", "rì chū", "sunrise", "matahari terbit"],
    ["或", "huò", "or", "atau"],
    ["日落时", "rì luò shí", "sunset", "matahari terbenam"],
    ["，", "", "", ""],
    ["有时", "yǒu shí", "sometimes", "kadang-kadang"],
    ["也会", "yě huì", "also will", "juga akan"],
    ["看到", "kàn dào", "see", "melihat"],
    ["扁圆形的", "biǎn yuán xíng de", "oblate", "bujur"],
    ["太阳", "tài yáng", "sun", "matahari"],
    ["。", "", "", ""],
    ["早在", "zǎo zài", "As early as", "Seawal"],
    ["两千多年前", "liǎng qiān duō nián qián", "over two thousand years ago", "lebih dua ribu tahun lalu"],
    ["，", "", "", ""],
    ["中国古代", "zhōng guó gǔ dài", "ancient Chinese", "China purba"],
    ["的", "de", "", ""],
    ["诗人", "shī rén", "poets", "penyair"],
    ["就", "jiù", "already", "telah"],
    ["曾", "céng", "once", "pernah"],
    ["敏锐地", "mǐn ruì de", "keenly", "dengan tajam"],
    ["观察到", "guān chá dào", "observed", "memerhatikan"],
    ["这一现象", "zhè yī xiàn xiàng", "this phenomenon", "fenomena ini"],
    ["。", "", "", ""],
    ["例如", "lì rú", "For example", "Contohnya"],
    ["，", "", "", ""],
    ["汉代", "hàn dài", "Han Dynasty", "Dinasti Han"],
    ["苏武", "sū wǔ", "Su Wu", "Su Wu"],
    ["的", "de", "", ""],
    ["“", "", "", ""],
    ["日出如破镜", "rì chū rú pò jìng", "The sunrise is like a broken mirror", "Matahari terbit seperti cermin pecah"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["南朝", "nán cháo", "Southern Dynasty", "Dinasti Selatan"],
    ["鲍照", "bào zhào", "Bao Zhao", "Bao Zhao"],
    ["的", "de", "", ""],
    ["“", "", "", ""],
    ["平原落日扁", "píng yuán luò rì biǎn", "The setting sun is flat over the plain", "Matahari terbenam leper di dataran"],
    ["”", "", "", ""],
    ["等", "děng", "etc.", "dan lain-lain"],
    ["。", "", "", ""],
    ["那么", "nà me", "So", "Jadi"],
    ["，", "", "", ""],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["落日", "luò rì", "the setting sun", "matahari terbenam"],
    ["会变", "huì biàn", "becomes", "menjadi"],
    ["“", "", "", ""],
    ["扁", "biǎn", "flat", "leper"],
    ["”", "", "", ""],
    ["呢", "ne", "", ""],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["原来", "yuán lái", "It turns out", "Rupanya"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["主要是", "zhǔ yào shì", "is mainly", "terutamanya"],
    ["大气的", "dà qì de", "atmospheric", "atmosfera punya"],
    ["折射现象", "zhé shè xiàn xiàng", "refraction phenomenon", "fenomena pembiasan"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "We", "Kita"],
    ["知道", "zhī dào", "know", "tahu"],
    ["，", "", "", ""],
    ["地球", "dì qiú", "Earth's", "Bumi punya"],
    ["大气层", "dà qì céng", "atmosphere", "lapisan atmosfera"],
    ["是", "shì", "is", "ialah"],
    ["不均匀的", "bù jūn yún de", "uneven", "tidak seragam"],
    ["，", "", "", ""],
    ["越靠近", "yuè kào jìn", "the closer to", "semakin dekat"],
    ["地面", "dì miàn", "the ground", "tanah"],
    ["，", "", "", ""],
    ["大气的", "dà qì de", "atmosphere's", "atmosfera punya"],
    ["密度", "mì dù", "density", "ketumpatan"],
    ["越大", "yuè dà", "greater", "semakin besar"],
    ["，", "", "", ""],
    ["折射率", "zhé shè lǜ", "refractive index", "indeks biasan"],
    ["也就", "yě jiù", "also", "juga"],
    ["越大", "yuè dà", "greater", "semakin besar"],
    ["。", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["太阳", "tài yáng", "the sun", "matahari"],
    ["落向", "luò xiàng", "sets toward", "terbenam ke arah"],
    ["地平线时", "dì píng xiàn shí", "the horizon", "ufuk"],
    ["，", "", "", ""],
    ["太阳光", "tài yáng guāng", "sunlight", "cahaya matahari"],
    ["是", "shì", "is", "ialah"],
    ["通过", "tōng guò", "through", "melalui"],
    ["大气层", "dà qì céng", "the atmosphere", "lapisan atmosfera"],
    ["进入", "jìn rù", "entering", "masuk ke"],
    ["我们的", "wǒ men de", "our", "kita punya"],
    ["眼睛的", "yǎn jīng de", "eyes", "mata"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "Because", "Kerana"],
    ["太阳的", "tài yáng de", "the sun's", "matahari punya"],
    ["下部光线", "xià bù guāng xiàn", "lower rays", "sinaran bawah"],
    ["比", "bǐ", "than", "daripada"],
    ["上部光线", "shàng bù guāng xiàn", "upper rays", "sinaran atas"],
    ["所", "suǒ", "", ""],
    ["经过的", "jīng guò de", "pass through", "melalui"],
    ["大气", "dà qì", "atmosphere", "atmosfera"],
    ["折射作用", "zhé shè zuò yòng", "refraction", "pembiasan"],
    ["更强", "gèng qiáng", "stronger", "lebih kuat"],
    ["，", "", "", ""],
    ["这就", "zhè jiù", "this makes", "ini menjadikan"],
    ["使得", "shǐ de", "causes", "menyebabkan"],
    ["太阳的", "tài yáng de", "the sun's", "matahari punya"],
    ["下部", "xià bù", "lower part", "bahagian bawah"],
    ["向上弯曲", "xiàng shàng wān qū", "bend upward", "melengkung ke atas"],
    ["得", "de", "", ""],
    ["比", "bǐ", "than", "daripada"],
    ["上部", "shàng bù", "upper part", "bahagian atas"],
    ["多一些", "duō yī xiē", "more", "lebih"],
    ["。", "", "", ""],
    ["结果", "jié guǒ", "As a result", "Hasilnya"],
    ["，", "", "", ""],
    ["在", "zài", "in", "pada"],
    ["我们的", "wǒ men de", "our", "kita punya"],
    ["视线中", "shì xiàn zhōng", "sight", "pandangan"],
    ["，", "", "", ""],
    ["太阳的", "tài yáng de", "the sun's", "matahari punya"],
    ["垂直直径", "chuí zhí zhí jìng", "vertical diameter", "diameter menegak"],
    ["缩短了", "suō duǎn le", "shortens", "memendek"],
    ["，", "", "", ""],
    ["而", "ér", "while", "manakala"],
    ["水平直径", "shuǐ píng zhí jìng", "horizontal diameter", "diameter mendatar"],
    ["并没有改变", "bìng méi yǒu gǎi biàn", "does not change", "tidak berubah"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "Therefore", "Maka"],
    ["，", "", "", ""],
    ["圆形", "yuán xíng", "round", "bulat"],
    ["就", "jiù", "then", "maka"],
    ["变成了", "biàn chéng le", "becomes", "menjadi"],
    ["扁圆形", "biǎn yuán xíng", "oblate", "bujur"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["折射现象", "zhé shè xiàn xiàng", "Refraction", "Pembiasan"],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["会改变", "huì gǎi biàn", "can change", "boleh mengubah"],
    ["太阳的", "tài yáng de", "the sun's", "matahari punya"],
    ["形状", "xíng zhuàng", "shape", "bentuk"],
    ["，", "", "", ""],
    ["还会", "hái huì", "but also", "juga akan"],
    ["改变", "gǎi biàn", "change", "mengubah"],
    ["太阳的", "tài yáng de", "the sun's", "matahari punya"],
    ["位置", "wèi zhì", "position", "kedudukan"],
    ["。", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["太阳的", "tài yáng de", "the sun's", "matahari punya"],
    ["下边缘", "xià biān yuán", "lower edge", "tepi bawah"],
    ["刚", "gāng", "just", "baru"],
    ["触及", "chù jí", "touches", "menyentuh"],
    ["地平线时", "dì píng xiàn shí", "the horizon", "ufuk"],
    ["，", "", "", ""],
    ["由于", "yóu yú", "because", "kerana"],
    ["大气的折射", "dà qì de zhé shè", "atmospheric refraction", "pembiasan atmosfera"],
    ["，", "", "", ""],
    ["实际上", "shí jì shàng", "in fact", "sebenarnya"],
    ["它", "tā", "it", "ia"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["在", "zài", "below", "di bawah"],
    ["地平线之下了", "dì píng xiàn zhī xià le", "the horizon", "ufuk"],
    ["。", "", "", ""],
    ["也就是说", "yě jiù shì shuō", "In other words", "Dengan kata lain"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["所看到的", "suǒ kàn dào de", "what we see", "apa yang kita lihat"],
    ["落日", "luò rì", "setting sun", "matahari terbenam"],
    ["，", "", "", ""],
    ["其实", "qí shí", "actually", "sebenarnya"],
    ["只是", "zhǐ shì", "is only", "hanyalah"],
    ["它的", "tā de", "its", "ia punya"],
    ["虚像", "xū xiàng", "virtual image", "imej maya"],
    ["。", "", "", ""],
    ["这种", "zhè zhǒng", "This kind of", "Jenis ini"],
    ["现象", "xiàn xiàng", "phenomenon", "fenomena"],
    ["在", "zài", "in", "di"],
    ["气温差异", "qì wēn chā yì", "temperature difference", "perbezaan suhu"],
    ["极大的", "jí dà de", "extreme", "sangat besar"],
    ["地方", "dì fang", "places", "tempat-tempat"],
    ["，", "", "", ""],
    ["如", "rú", "such as", "seperti"],
    ["大沙漠中", "dà shā mò zhōng", "in the great desert", "di padang pasir"],
    ["更为明显", "gèng wéi míng xiǎn", "more obvious", "lebih jelas"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["其实", "qí shí", "In fact", "Sebenarnya"],
    ["，", "", "", ""],
    ["这种", "zhè zhǒng", "this kind of", "jenis ini"],
    ["大气的", "dà qì de", "atmospheric", "atmosfera punya"],
    ["折射现象", "zhé shè xiàn xiàng", "refraction", "pembiasan"],
    ["在", "zài", "in", "dalam"],
    ["日常生活中", "rì cháng shēng huó zhōng", "daily life", "kehidupan seharian"],
    ["也", "yě", "also", "juga"],
    ["随处可见", "suí chù kě jiàn", "can be seen everywhere", "boleh dilihat di mana-mana"],
    ["。", "", "", ""],
    ["当你", "dāng nǐ", "When you", "Apabila awak"],
    ["把", "bǎ", "", ""],
    ["一支筷子", "yī zhī kuài zi", "a chopstick", "sebatang penyepit"],
    ["斜插进", "xié chā jìn", "obliquely insert into", "menyumbat secara condong ke"],
    ["装满水", "zhuāng mǎn shuǐ", "filled with water", "dipenuhi air"],
    ["的", "de", "", ""],
    ["杯子里时", "bēi zi lǐ shí", "cup", "cawan"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["会发现", "huì fā xiàn", "will find", "akan mendapati"],
    ["筷子", "kuài zi", "the chopstick", "penyepit"],
    ["好像", "hǎo xiàng", "seems", "seolah-olah"],
    ["折断了", "zhé duàn le", "broken", "patah"],
    ["。", "", "", ""],
    ["当你", "dāng nǐ", "When you", "Apabila awak"],
    ["站在", "zhàn zài", "stand at", "berdiri di"],
    ["清澈的", "qīng chè de", "clear", "jernih"],
    ["池塘边", "chí táng biān", "pond", "kolam"],
    ["向水里看时", "xiàng shuǐ lǐ kàn shí", "look into the water", "melihat ke dalam air"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["会发现", "huì fā xiàn", "will find", "akan mendapati"],
    ["池底", "chí dǐ", "the bottom of the pond", "dasar kolam"],
    ["好像", "hǎo xiàng", "seems", "seolah-olah"],
    ["变浅了", "biàn qiǎn le", "shallower", "menjadi cetek"],
    ["。", "", "", ""],
    ["这些", "zhè xiē", "These", "Ini"],
    ["都是", "dōu shì", "are all", "semuanya"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["光", "guāng", "light", "cahaya"],
    ["在", "zài", "in", "dalam"],
    ["通过", "tōng guò", "passing through", "melalui"],
    ["密度不同", "mì dù bù tóng", "different density", "ketumpatan berbeza"],
    ["的", "de", "", ""],
    ["介质时", "jiè zhì shí", "medium", "medium"],
    ["，", "", "", ""],
    ["发生了", "fā shēng le", "occurs", "berlaku"],
    ["折射", "zhé shè", "refraction", "pembiasan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["由此可见", "yóu cǐ kě jiàn", "Thus it can be seen", "Dengan ini dapat dilihat"],
    ["，", "", "", ""],
    ["大自然中", "dà zì rán zhōng", "In nature", "Dalam alam semula jadi"],
    ["处处", "chù chù", "everywhere", "di mana-mana"],
    ["充满了", "chōng mǎn le", "is full of", "penuh dengan"],
    ["科学的", "kē xué de", "scientific", "saintifik"],
    ["奥秘", "ào mì", "mysteries", "misteri"],
    ["。", "", "", ""],
    ["只有", "zhǐ yǒu", "Only by", "Hanya dengan"],
    ["通过", "tōng guò", "through", "melalui"],
    ["细致的", "xì zhì de", "careful", "teliti"],
    ["观察", "guān chá", "observation", "pemerhatian"],
    ["和", "hé", "and", "dan"],
    ["科学的", "kē xué de", "scientific", "saintifik"],
    ["分析", "fēn xī", "analysis", "analisis"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["才能", "cái néng", "can", "baru boleh"],
    ["揭开", "jiē kāi", "uncover", "membongkar"],
    ["大自然的", "dà zì rán de", "nature's", "alam semula jadi punya"],
    ["神秘面纱", "shén mì miàn shā", "mysterious veil", "tabir misteri"],
    ["。", "", "", ""],
    ["王维的", "wáng wéi de", "Wang Wei's", "Wang Wei punya"],
    ["“", "", "", ""],
    ["长河落日圆", "cháng hé luò rì yuán", "The setting sun is round over the long river", "Matahari terbenam bulat di atas sungai panjang"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["固然是", "gù rán shì", "certainly is", "memang"],
    ["艺术上的", "yì shù shàng de", "artistic", "seni"],
    ["升华", "shēng huá", "elevation", "peningkatan"],
    ["和", "hé", "and", "dan"],
    ["美化", "měi huà", "beautification", "penghiasan"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["苏武的", "sū wǔ de", "Su Wu's", "Su Wu punya"],
    ["“", "", "", ""],
    ["日出如破镜", "rì chū rú pò jìng", "sunrise like a broken mirror", "matahari terbit seperti cermin pecah"],
    ["”", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["鲍照的", "bào zhào de", "Bao Zhao's", "Bao Zhao punya"],
    ["“", "", "", ""],
    ["平原落日扁", "píng yuán luò rì biǎn", "setting sun flat over the plain", "matahari terbenam leper di dataran"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["却", "què", "however", "sebaliknya"],
    ["更真实地", "gèng zhēn shí de", "more truly", "lebih benar"],
    ["反映了", "fǎn yìng le", "reflect", "mencerminkan"],
    ["自然界中", "zì rán jiè zhōng", "in nature", "dalam alam"],
    ["的", "de", "", ""],
    ["光学现象", "guāng xué xiàn xiàng", "optical phenomenon", "fenomena optik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["佚名", "yì míng", "Anonymous", "Tanpa Nama"],
    ["《", "", "", ""],
    ["长河落日扁", "cháng hé luò rì biǎn", "The Setting Sun is Flat", "Matahari Terbenam Leper"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
